services:

  mariadb:
    image: mariadb:11
    container_name: mariadb

    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: student_db
      MARIADB_USER: diwakar
      MARIADB_PASSWORD: linux7107

    volumes:
      - mariadb-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backendcn

    environment:
      DB_URL: jdbc:mariadb://mariadb:3306/student_db
      DB_USER: diwakar
      DB_PASSWORD: linux7107

    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    container_name: frontend

    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend

volumes:
  mariadb-data:
